[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  "modelo-bridge" = { timeout = 10 }

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[redirects]]
  from = "/api/modelo"
  to = "/.netlify/functions/modelo-bridge"
  status = 200
  force = true
